color_ref: cattpuccin
folder_mapings:
  '~/.local/share/icons/hicolor/0x0/apps': 'apps'
  '~/.local/share/icons/hicolor/16x16/apps': 'apps'
  '~/.local/share/icons/hicolor/24x24/apps': 'apps'
  '~/.local/share/icons/hicolor/32x32/apps': 'apps'
  '~/.local/share/icons/hicolor/48x48/apps': 'apps'
  '~/.local/share/icons/hicolor/64x64/apps': 'apps'
  '~/.local/share/icons/hicolor/96x96/apps': 'apps'
  '~/.local/share/icons/hicolor/128x128/apps': 'apps'
  '~/.local/share/icons/hicolor/256x256/apps': 'apps'
  '~/.local/share/icons/hicolor/512x512/apps': 'apps'
  '~/.local/share/icons/hicolor/1024x1024/apps': 'apps'
  '~/.local/share/icons/hicolor/scalable/apps': 'apps'
  '~/.local/share/icons/Catppuccin/actions/24': 'actions'
  '~/.local/share/icons/Catppuccin/devices/22': 'devices'
  '~/.local/share/icons/Catppuccin/emblems/48': 'emblems'
  '~/.local/share/icons/Catppuccin/mimetypes/64': 'mimetypes'
  '~/.local/share/icons/Catppuccin/panel/24': 'panel'
  '~/.local/share/icons/Catppuccin/places/64': 'places'
  '~/.local/share/icons/WhiteSur/status/24': 'status'
  '~/.local/share/icons/WhiteSur/animations/24': 'animations'
  '~/.local/share/icons/Nordic-Darker/Places': 'places'
  '~/.local/share/icons/Nordic-Darker/devices/48': 'devices'
  '~/.local/share/icons/Nordic-Darker/categories/22': 'categories'
  '~/.local/share/icons/Papirus-Colors/128x128/places': 'places'
  '~/.local/share/icons/WhiteSur/apps/scalable': 'apps'
  '~/.local/share/icons/Catppuccin/apps/64': 'apps'
  '~/.local/share/icons/Fluent-grey-dark/scalable/apps': 'apps'
  '~/.local/share/icons/WhiteSur-grey-dark/places/scalable': 'places'
